In [4]:
import os
print(os.getcwd())

c:\Users\sehut\OneDrive\Desktop\Analisis y desarrollo de software\Septimo Trimestre\Ciencia de datos con python\emisiones_vehiculos\notebooks

## 2. Carga de datos
Se cargan los dos datasets del proyecto, cada uno en su propio DataFrame:
- `df_co2`: CO2 Emission by Vehicles (Kaggle, datos de Canadá)
- `df_epa`: Vehicle Fuel Economy (Data.gov / EPA, datos de EE. UU.)

In [5]:
# Paso 1: importar Pandas, la librería para manejar tablas de datos
import pandas as pd

# Paso 2: cargar el Dataset 1 (Kaggle, Canadá) en el DataFrame df_co2
df_co2 = pd.read_csv("../data/raw/CO2 Emissions_Canada.csv")

# Paso 3: cargar el Dataset 2 (EPA, EE. UU.) en el DataFrame df_epa
# low_memory=False hace que Pandas lea todo el archivo antes de decidir
# el tipo de cada columna (el archivo es grande)
df_epa = pd.read_csv("../data/raw/fuel_economy_epa.csv", low_memory=False)

# Paso 4: verificar que ambos se cargaron (filas, columnas)
print("Dataset 1 (df_co2):", df_co2.shape)
print("Dataset 2 (df_epa):", df_epa.shape)

Dataset 1 (df_co2): (7385, 12)
Dataset 2 (df_epa): (50407, 84)

In [4]:
# Paso 5: leer el diccionario de datos del Dataset 1
# (es documentación de apoyo, no un dataset a diagnosticar)
descripcion_co2 = pd.read_csv("../data/raw/Data Description.csv")
descripcion_co2

   Understanding the Data                                         Unnamed: 1
0                   Model                         4WD/4X4 = Four-wheel drive
1                     NaN                              AWD = All-wheel drive
2                     NaN                        FFV = Flexible-fuel vehicle
3                     NaN                              SWB = Short wheelbase
4                     NaN                               LWB = Long wheelbase
5                     NaN                           EWB = Extended wheelbase
6            Transmission                                      A = automatic
7                     NaN                              AM = automated manual
8                     NaN                   AS = automatic with select shift
9                     NaN                         AV = continuously variable
10                    NaN                                         M = manual
11                    NaN                           3 - 10 = Number of gears
12              Fuel type                               X = regular gasoline
13                    NaN                               Z = premium gasoline
14                    NaN                                         D = diesel
15                    NaN                                  E = ethanol (E85)
16                    NaN                                    N = natural gas
17       Fuel consumption  City and highway fuel consumption ratings are ...
18          CO2 emissions  the tailpipe emissions of carbon dioxide (in g...

## 3. Inspección estructural
### 3.1 Dataset 1: df_co2 (CO2 Emission by Vehicles, Kaggle)

In [6]:
# head(): muestra los primeros 5 registros para ver cómo luce la información
df_co2.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [7]:
# tail(): muestra los últimos 5 registros para detectar filas sobrantes o raras
df_co2.tail()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [8]:
# shape: devuelve (número de filas, número de columnas)
df_co2.shape

(7385, 12)

In [9]:
# columns: lista los nombres de las variables
df_co2.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='str')

In [10]:
# dtypes: tipo de dato de cada columna (int, float, object)
df_co2.dtypes

Make                                    str
Model                                   str
Vehicle Class                           str
Engine Size(L)                      float64
Cylinders                             int64
Transmission                            str
Fuel Type                               str
Fuel Consumption City (L/100 km)    float64
Fuel Consumption Hwy (L/100 km)     float64
Fuel Consumption Comb (L/100 km)    float64
Fuel Consumption Comb (mpg)           int64
CO2 Emissions(g/km)                   int64
dtype: object

In [11]:
# info(): resumen de la estructura y valores no nulos por columna
df_co2.info()

<class 'pandas.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   str
 1   Model                             7385 non-null   str
 2   Vehicle Class                     7385 non-null   str
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   str
 6   Fuel Type                         7385 non-null   str
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), str(5)
memory usage: 692.5 KB

In [12]:
# describe(): estadísticas de las variables numéricas
df_co2.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,5.615030,12.556534,9.041706,10.975071,27.481652,250.584699
std,1.354170,1.828307,3.500274,2.224456,2.892506,7.231879,58.512679
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

In [13]:
# describe(include='object'): resumen de las variables de texto
df_co2.describe(include="object")

C:\Users\sehut\AppData\Local\Temp\ipykernel_29232\744705479.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/dev/user_guide/migration.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_co2.describe(include="object")

        Make      Model Vehicle Class Transmission Fuel Type
count   7385       7385          7385         7385      7385
unique    42       2053            16           27         5
top     FORD  F-150 FFV   SUV - SMALL          AS6         X
freq     628         32          1217         1324      3637

In [14]:
# Contar filas completamente duplicadas en df_co2
df_co2.duplicated().sum()

np.int64(1103)

**Observaciones del Dataset 1 (df_co2):**
- Tiene 7385 filas y 12 columnas. Cada fila representa una configuración de vehículo (marca, modelo y características) con su consumo y sus emisiones de CO₂.
- Tipos de datos: 4 columnas float64, 3 int64 y 5 de texto (str/object). Variables numéricas (7): Engine Size(L), Cylinders, Fuel Consumption City (L/100 km), Fuel Consumption Hwy (L/100 km), Fuel Consumption Comb (L/100 km), Fuel Consumption Comb (mpg) y CO2 Emissions(g/km), esta última es la variable objetivo de la pregunta analítica. Los tipos son coherentes con lo que representan.
- Variables de texto (5): Make (42 marcas; la más frecuente es FORD con 628 registros), Model (2053 valores distintos), Vehicle Class (16 clases; la más común es SUV - SMALL con 1217), Transmission (27 códigos; el más frecuente es AS6 con 1324) y Fuel Type (5 códigos; X, gasolina regular, domina con 3637).
- Valores faltantes: las 12 columnas tienen 7385 valores no nulos, es decir, no hay valores faltantes.
- Rangos en describe(): el tamaño del motor va de 0.9 a 8.4 L (media 3.16); los cilindros de 3 a 16 (media 5.6); el consumo combinado de 4.1 a 26.1 L/100 km; y las emisiones de 96 a 522 g/km (media 250.6 y mediana 246). No aparecen ceros ni valores negativos, y los rangos son plausibles para vehículos desde compactos hasta deportivos de alto desempeño. El máximo de emisiones (522) queda lejos del percentil 75 (288), por lo que conviene revisar posibles valores atípicos más adelante.
- Duplicados: se encontraron 1103 filas duplicadas con duplicated().sum(), cerca del 14,9 % de los registros. Pueden distorsionar promedios y correlaciones, por lo que deberán revisarse antes del análisis.
- Nombres de columnas: tienen espacios, paréntesis, mayúsculas y símbolos (por ejemplo "Engine Size(L)" y "CO2 Emissions(g/km)"), con formatos poco uniformes. Convendrá estandarizarlos más adelante.
- Códigos: Transmission y Fuel Type usan abreviaturas (AS6, M6; X, Z, D, E, N) que solo se entienden con el diccionario de datos.
- Limitaciones: el consumo aparece en dos unidades (L/100 km y mpg), lo que duplica información y podría generar redundancia al analizar. Además, el dataset no incluye año del modelo ni vehículos eléctricos o híbridos (los tipos de combustible son gasolina, diésel, etanol y gas natural).

| Dataset | Filas | Columnas | Tipos de datos | Observaciones |
|---|---|---|---|---|
| df_co2 (Kaggle, Canadá) | 7385 | 12 | float64 (4), int64 (3), str/object (5) | Duplicados: se encontraron 1103 filas duplicadas con duplicated().sum(), cerca del 14,9 % de los registros. Pueden distorsionar promedios y correlaciones, por lo que deberán revisarse antes del análisis. |