# Diagnóstico de calidad de datos: emisiones de CO₂ en vehículos

Notebook de preparación, exploración y documentación de la calidad de los dos datasets del proyecto, usando Pandas.

## 1. Configuración del entorno

In [1]:
# Verificar el directorio de trabajo (debe ser la carpeta notebooks)
import os
print(os.getcwd())

c:\Users\sehut\OneDrive\Desktop\Analisis y desarrollo de software\Septimo Trimestre\Ciencia de datos con python\emisiones_vehiculos\notebooks

## 2. Carga de datos
Se cargan los dos datasets del proyecto, cada uno en su propio DataFrame:
- `df_co2`: CO2 Emission by Vehicles (Kaggle, datos de Canadá)
- `df_epa`: Vehicle Fuel Economy (Data.gov / EPA, datos de EE. UU.)

In [2]:
# Paso 1: importar Pandas, la librería para manejar tablas de datos
import pandas as pd

# Paso 2: cargar el Dataset 1 (Kaggle, Canadá) en el DataFrame df_co2
df_co2 = pd.read_csv("../data/raw/CO2 Emissions_Canada.csv")

# Paso 3: cargar el Dataset 2 (EPA, EE. UU.) en el DataFrame df_epa
# low_memory=False hace que Pandas lea todo el archivo antes de decidir
# el tipo de cada columna (el archivo es grande)
df_epa = pd.read_csv("../data/raw/fuel_economy_epa.csv", low_memory=False)

# Paso 4: verificar que ambos se cargaron (filas, columnas)
print("Dataset 1 (df_co2):", df_co2.shape)
print("Dataset 2 (df_epa):", df_epa.shape)

Dataset 1 (df_co2): (7385, 12)
Dataset 2 (df_epa): (50407, 84)

In [3]:
# Paso 5: leer el diccionario de datos del Dataset 1
# (es documentación de apoyo, no un dataset a diagnosticar)
descripcion_co2 = pd.read_csv("../data/raw/Data Description.csv")
descripcion_co2

   Understanding the Data                                         Unnamed: 1
0                   Model                         4WD/4X4 = Four-wheel drive
1                     NaN                              AWD = All-wheel drive
2                     NaN                        FFV = Flexible-fuel vehicle
3                     NaN                              SWB = Short wheelbase
4                     NaN                               LWB = Long wheelbase
5                     NaN                           EWB = Extended wheelbase
6            Transmission                                      A = automatic
7                     NaN                              AM = automated manual
8                     NaN                   AS = automatic with select shift
9                     NaN                         AV = continuously variable
10                    NaN                                         M = manual
11                    NaN                           3 - 10 = Number of gears
12              Fuel type                               X = regular gasoline
13                    NaN                               Z = premium gasoline
14                    NaN                                         D = diesel
15                    NaN                                  E = ethanol (E85)
16                    NaN                                    N = natural gas
17       Fuel consumption  City and highway fuel consumption ratings are ...
18          CO2 emissions  the tailpipe emissions of carbon dioxide (in g...

## 3. Inspección estructural
### 3.1 Dataset 1: df_co2 (CO2 Emission by Vehicles, Kaggle)

In [4]:
# head(): muestra los primeros 5 registros para ver cómo luce la información
df_co2.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [5]:
# tail(): muestra los últimos 5 registros para detectar filas sobrantes o raras
df_co2.tail()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [6]:
# shape: devuelve (número de filas, número de columnas)
df_co2.shape

(7385, 12)

In [7]:
# columns: lista los nombres de las variables
df_co2.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='str')

In [8]:
# dtypes: tipo de dato de cada columna (int, float, object)
df_co2.dtypes

Make                                    str
Model                                   str
Vehicle Class                           str
Engine Size(L)                      float64
Cylinders                             int64
Transmission                            str
Fuel Type                               str
Fuel Consumption City (L/100 km)    float64
Fuel Consumption Hwy (L/100 km)     float64
Fuel Consumption Comb (L/100 km)    float64
Fuel Consumption Comb (mpg)           int64
CO2 Emissions(g/km)                   int64
dtype: object

In [9]:
# info(): resumen de la estructura y valores no nulos por columna
df_co2.info()

<class 'pandas.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   str
 1   Model                             7385 non-null   str
 2   Vehicle Class                     7385 non-null   str
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   str
 6   Fuel Type                         7385 non-null   str
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), str(5)
memory usage: 692.5 KB

In [10]:
# describe(): estadísticas de las variables numéricas
df_co2.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,5.615030,12.556534,9.041706,10.975071,27.481652,250.584699
std,1.354170,1.828307,3.500274,2.224456,2.892506,7.231879,58.512679
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

In [11]:
# describe(include='str'): resumen de las variables de texto
# (en pandas 3 el texto es tipo str; 'object' genera una advertencia de obsolescencia)
df_co2.describe(include="str")

        Make      Model Vehicle Class Transmission Fuel Type
count   7385       7385          7385         7385      7385
unique    42       2053            16           27         5
top     FORD  F-150 FFV   SUV - SMALL          AS6         X
freq     628         32          1217         1324      3637

In [12]:
# Contar filas completamente duplicadas en df_co2
df_co2.duplicated().sum()

np.int64(1103)

**Observaciones del Dataset 1 (df_co2):**
- Tiene 7385 filas y 12 columnas. Cada fila representa una configuración de vehículo (marca, modelo y características) con su consumo y sus emisiones de CO₂.
- Tipos de datos: 4 columnas float64, 3 int64 y 5 de texto (str/object). Variables numéricas (7): Engine Size(L), Cylinders, Fuel Consumption City (L/100 km), Fuel Consumption Hwy (L/100 km), Fuel Consumption Comb (L/100 km), Fuel Consumption Comb (mpg) y CO2 Emissions(g/km), esta última es la variable objetivo de la pregunta analítica. Los tipos son coherentes con lo que representan.
- Variables de texto (5): Make (42 marcas; la más frecuente es FORD con 628 registros), Model (2053 valores distintos), Vehicle Class (16 clases; la más común es SUV - SMALL con 1217), Transmission (27 códigos; el más frecuente es AS6 con 1324) y Fuel Type (5 códigos; X, gasolina regular, domina con 3637).
- Valores faltantes: las 12 columnas tienen 7385 valores no nulos, es decir, no hay valores faltantes.
- Rangos en describe(): el tamaño del motor va de 0.9 a 8.4 L (media 3.16); los cilindros de 3 a 16 (media 5.6); el consumo combinado de 4.1 a 26.1 L/100 km; y las emisiones de 96 a 522 g/km (media 250.6 y mediana 246). No aparecen ceros ni valores negativos, y los rangos son plausibles para vehículos desde compactos hasta deportivos de alto desempeño. El máximo de emisiones (522) queda lejos del percentil 75 (288), por lo que conviene revisar posibles valores atípicos más adelante.
- Duplicados: se encontraron 1103 filas duplicadas con duplicated().sum(), cerca del 14,9 % de los registros. Pueden distorsionar promedios y correlaciones, por lo que deberán revisarse antes del análisis.
- Nombres de columnas: tienen espacios, paréntesis, mayúsculas y símbolos (por ejemplo "Engine Size(L)" y "CO2 Emissions(g/km)"), con formatos poco uniformes. Convendrá estandarizarlos más adelante.
- Códigos: Transmission y Fuel Type usan abreviaturas (AS6, M6; X, Z, D, E, N) que solo se entienden con el diccionario de datos.
- Limitaciones: el consumo aparece en dos unidades (L/100 km y mpg), lo que duplica información y podría generar redundancia al analizar. Además, el dataset no incluye año del modelo ni vehículos eléctricos o híbridos (los tipos de combustible son gasolina, diésel, etanol y gas natural).

### 3.2 Dataset 2: df_epa (Vehicle Fuel Economy, EPA / Data.gov)

In [13]:
# Mostrar todas las columnas y filas en las salidas largas
# (df_epa tiene 84 columnas y Pandas oculta las del medio)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [14]:
# Primeras 5 filas: vista general de los registros del dataset EPA
df_epa.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,baseModel,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,14.167143,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,3200,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-4000,Spider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,27.046364,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,6100,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-18500,Testarossa,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,11.018889,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,2500,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,-500,Charger,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,27.046364,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,6100,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-18500,B150/B250 Wagon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,15.658421,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,4350,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-9750,Legacy/Outback,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [15]:
# Últimas 5 filas: verificar que el archivo cargó completo hasta el final
df_epa.tail()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,baseModel,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
50402,13.523182,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,3050,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,24.0,0.0,37.0,0.0,Compact Cars,1993,-3250,Legacy/Outback,NaN,CLKUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
50403,12.935217,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2900,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,25.0,0.0,39.0,0.0,Compact Cars,1993,-2500,Legacy/Outback,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
50404,14.167143,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,3200,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,23.0,0.0,34.0,0.0,Compact Cars,1993,-4000,Legacy/Outback,NaN,CLKUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
50405,14.167143,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,3200,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.0,0.0,34.0,0.0,Compact Cars,1993,-4000,Legacy/Outback,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
50406,16.528333,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,4550,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,20.0,0.0,29.0,0.0,Compact Cars,1993,-10750,Legacy/Outback,NaN,CLKUP,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [16]:
# Dimensiones: (filas, columnas)
df_epa.shape

(50407, 84)

In [17]:
# Nombres de las 84 columnas
df_epa.columns

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD',
       'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make',
       'model', 'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'baseModel',
       'guzzler', 'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2',
       'rangeA', 'evMotor', 'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr',
       'createdOn', 'modifiedOn', 'startStop', 'phevCity', 'phevHwy',
       'phevComb'],
      dtype='str')

In [18]:
# Tipo de dato de cada columna
df_epa.dtypes

barrels08          float64
barrelsA08         float64
charge120          float64
charge240          float64
city08               int64
city08U            float64
cityA08              int64
cityA08U           float64
cityCD             float64
cityE              float64
cityUF             float64
co2                  int64
co2A                 int64
co2TailpipeAGpm    float64
co2TailpipeGpm     float64
comb08               int64
comb08U            float64
combA08              int64
combA08U           float64
combE              float64
combinedCD         float64
combinedUF         float64
cylinders          float64
displ              float64
drive                  str
engId                int64
eng_dscr               str
feScore              int64
fuelCost08           int64
fuelCostA08          int64
fuelType               str
fuelType1              str
ghgScore             int64
ghgScoreA            int64
highway08            int64
highway08U         float64
highwayA08           int64
highwayA08U        float64
highwayCD          float64
highwayE           float64
highwayUF          float64
hlv                  int64
hpv                  int64
id                   int64
lv2                  int64
lv4                  int64
make                   str
model                  str
mpgData                str
phevBlended           bool
pv2                  int64
pv4                  int64
range                int64
rangeCity          float64
rangeCityA         float64
rangeHwy           float64
rangeHwyA          float64
trany                  str
UCity              float64
UCityA             float64
UHighway           float64
UHighwayA          float64
VClass                 str
year                 int64
youSaveSpend         int64
baseModel              str
guzzler                str
trans_dscr             str
tCharger               str
sCharger               str
atvType                str
fuelType2              str
rangeA                 str
evMotor                str
mfrCode                str
c240Dscr               str
charge240b         float64
c240bDscr              str
createdOn              str
modifiedOn             str
startStop              str
phevCity             int64
phevHwy              int64
phevComb             int64
dtype: object

In [19]:
# Resumen estructural: tipos, valores no nulos y uso de memoria
df_epa.info()

<class 'pandas.DataFrame'>
RangeIndex: 50407 entries, 0 to 50406
Data columns (total 84 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        50407 non-null  float64
 1   barrelsA08       50407 non-null  float64
 2   charge120        50407 non-null  float64
 3   charge240        50407 non-null  float64
 4   city08           50407 non-null  int64
 5   city08U          50407 non-null  float64
 6   cityA08          50407 non-null  int64
 7   cityA08U         50407 non-null  float64
 8   cityCD           50407 non-null  float64
 9   cityE            50407 non-null  float64
 10  cityUF           50407 non-null  float64
 11  co2              50407 non-null  int64
 12  co2A             50407 non-null  int64
 13  co2TailpipeAGpm  50407 non-null  float64
 14  co2TailpipeGpm   50407 non-null  float64
 15  comb08           50407 non-null  int64
 16  comb08U          50407 non-null  float64
 17  combA08          50407 non-null  int64
 18  combA08U         50407 non-null  float64
 19  combE            50407 non-null  float64
 20  combinedCD       50407 non-null  float64
 21  combinedUF       50407 non-null  float64
 22  cylinders        48752 non-null  float64
 23  displ            48754 non-null  float64
 24  drive            49221 non-null  str
 25  engId            50407 non-null  int64
 26  eng_dscr         31971 non-null  str
 27  feScore          50407 non-null  int64
 28  fuelCost08       50407 non-null  int64
 29  fuelCostA08      50407 non-null  int64
 30  fuelType         50407 non-null  str
 31  fuelType1        50405 non-null  str
 32  ghgScore         50407 non-null  int64
 33  ghgScoreA        50407 non-null  int64
 34  highway08        50407 non-null  int64
 35  highway08U       50407 non-null  float64
 36  highwayA08       50407 non-null  int64
 37  highwayA08U      50407 non-null  float64
 38  highwayCD        50407 non-null  float64
 39  highwayE         50407 non-null  float64
 40  highwayUF        50407 non-null  float64
 41  hlv              50407 non-null  int64
 42  hpv              50407 non-null  int64
 43  id               50407 non-null  int64
 44  lv2              50407 non-null  int64
 45  lv4              50407 non-null  int64
 46  make             50407 non-null  str
 47  model            50407 non-null  str
 48  mpgData          50407 non-null  str
 49  phevBlended      50407 non-null  bool
 50  pv2              50407 non-null  int64
 51  pv4              50407 non-null  int64
 52  range            50407 non-null  int64
 53  rangeCity        50407 non-null  float64
 54  rangeCityA       50407 non-null  float64
 55  rangeHwy         50407 non-null  float64
 56  rangeHwyA        50407 non-null  float64
 57  trany            50396 non-null  str
 58  UCity            50407 non-null  float64
 59  UCityA           50407 non-null  float64
 60  UHighway         50407 non-null  float64
 61  UHighwayA        50407 non-null  float64
 62  VClass           50407 non-null  str
 63  year             50407 non-null  int64
 64  youSaveSpend     50407 non-null  int64
 65  baseModel        50407 non-null  str
 66  guzzler          2859 non-null   str
 67  trans_dscr       15044 non-null  str
 68  tCharger         11787 non-null  str
 69  sCharger         1167 non-null   str
 70  atvType          6860 non-null   str
 71  fuelType2        2013 non-null   str
 72  rangeA           2010 non-null   str
 73  evMotor          3636 non-null   str
 74  mfrCode          19599 non-null  str
 75  c240Dscr         141 non-null    str
 76  charge240b       50407 non-null  float64
 77  c240bDscr        135 non-null    str
 78  createdOn        50407 non-null  str
 79  modifiedOn       50407 non-null  str
 80  startStop        18718 non-null  str
 81  phevCity         50407 non-null  int64
 82  phevHwy          50407 non-null  int64
 83  phevComb         50407 non-null  int64
dtypes: bool(1), float64(32), int64(27), str(24)
memory usage: 32.0 MB

In [20]:
# Estadísticas descriptivas de las columnas numéricas (transpuesta para leer mejor)
df_epa.describe().T

,count,mean,std,min,25%,50%,75%,max
barrels08,50407.0,14.838048,4.847023,0.047081,12.396250,14.8755,17.500588,42.501429
barrelsA08,50407.0,0.191641,0.984561,0.000000,0.000000,0.0000,0.000000,16.528333
charge120,50407.0,0.000063,0.014253,0.000000,0.000000,0.0000,0.000000,3.200000
charge240,50407.0,0.354740,1.896633,0.000000,0.000000,0.0000,0.000000,19.000000
city08,50407.0,21.068205,15.609411,6.000000,15.000000,18.0000,21.000000,153.000000
city08U,50407.0,10.960543,19.532638,0.000000,0.000000,0.0000,18.561100,155.824200
cityA08,50407.0,0.977106,7.246179,0.000000,0.000000,0.0000,0.000000,145.000000
cityA08U,50407.0,0.854756,7.179842,0.000000,0.000000,0.0000,0.000000,145.083500
cityCD,50407.0,0.000698,0.038652,0.000000,0.000000,0.0000,0.000000,5.350000
cityE,50407.0,1.655791,8.369548,0.000000,0.000000,0.0000,0.000000,122.000000
cityUF,50407.0,0.004636,0.050984,0.000000,0.000000,0.0000,0.000000,0.927000
co2,50407.0,134.157478,200.691381,-1.000000,-1.000000,-1.0000,333.000000,979.000000
co2A,50407.0,5.486262,55.519060,-1.000000,-1.000000,-1.0000,-1.000000,713.000000
co2TailpipeAGpm,50407.0,15.360644,87.455362,0.000000,0.000000,0.0000,0.000000,713.000000
co2TailpipeGpm,50407.0,442.866685,144.195574,0.000000,370.291667,444.3500,522.764706,1269.571429
comb08,50407.0,23.103319,14.411828,7.000000,17.000000,20.0000,24.000000,146.000000
comb08U,50407.0,11.729267,19.235896,0.000000,0.000000,0.0000,21.080400,145.650600
combA08,50407.0,1.021941,7.147956,0.000000,0.000000,0.0000,0.000000,133.000000
combA08U,50407.0,0.881385,7.053365,0.000000,0.000000,0.0000,0.000000,133.266200
combE,50407.0,1.705787,8.539984,0.000000,0.000000,0.0000,0.000000,121.000000
combinedCD,50407.0,0.000648,0.037227,0.000000,0.000000,0.0000,0.000000,4.800000
combinedUF,50407.0,0.004598,0.050490,0.000000,0.000000,0.0000,0.000000,0.920000
cylinders,48752.0,5.689120,1.773348,2.000000,4.000000,6.0000,6.000000,16.000000
displ,48754.0,3.261384,1.349133,0.000000,2.100000,3.0000,4.200000,8.400000
engId,50407.0,6716.681731,15890.804470,0.000000,1.000000,167.0000,3605.000000,69102.000000
feScore,50407.0,1.278711,3.257451,-1.000000,-1.000000,-1.0000,4.000000,10.000000
fuelCost08,50407.0,3653.167219,1146.967306,0.000000,2900.000000,3550.0000,4350.000000,11750.000000
fuelCostA08,50407.0,122.324280,689.762494,0.000000,0.000000,0.0000,0.000000,5500.000000
ghgScore,50407.0,1.302696,3.317622,-1.000000,-1.000000,-1.0000,4.000000,10.000000
ghgScoreA,50407.0,-0.916262,0.714094,-1.000000,-1.000000,-1.0000,-1.000000,10.000000
highway08,50407.0,26.702660,13.158803,9.000000,20.000000,24.0000,29.000000,142.000000
highway08U,50407.0,13.137512,19.556171,0.000000,0.000000,0.0000,25.412800,141.704600
highwayA08,50407.0,1.108656,7.209801,0.000000,0.000000,0.0000,0.000000,121.000000
highwayA08U,50407.0,0.939243,7.059028,0.000000,0.000000,0.0000,0.000000,121.200500
highwayCD,50407.0,0.000248,0.026564,0.000000,0.000000,0.0000,0.000000,4.060000
highwayE,50407.0,1.765809,8.774783,0.000000,0.000000,0.0000,0.000000,120.000000
highwayUF,50407.0,0.004545,0.049859,0.000000,0.000000,0.0000,0.000000,0.910000
hlv,50407.0,1.876545,5.822448,0.000000,0.000000,0.0000,0.000000,49.000000
hpv,50407.0,9.431627,27.112542,0.000000,0.000000,0.0000,0.000000,195.000000
id,50407.0,25384.575674,14721.413993,1.000000,12602.500000,25386.0000,38170.500000,50875.000000
lv2,50407.0,1.657468,4.173084,0.000000,0.000000,0.0000,0.000000,41.000000
lv4,50407.0,5.849842,9.432003,0.000000,0.000000,0.0000,13.000000,55.000000
pv2,50407.0,12.641954,30.162497,0.000000,0.000000,0.0000,0.000000,194.000000
pv4,50407.0,32.669113,45.889249,0.000000,0.000000,0.0000,91.000000,192.000000
range,50407.0,12.936160,65.708840,0.000000,0.000000,0.0000,0.000000,640.000000
rangeCity,50407.0,8.264975,50.285249,0.000000,0.000000,0.0000,0.000000,539.000000
rangeCityA,50407.0,0.248852,3.152252,0.000000,0.000000,0.0000,0.000000,135.280000
rangeHwy,50407.0,7.461245,45.488437,0.000000,0.000000,0.0000,0.000000,520.500000
rangeHwyA,50407.0,0.236660,2.919106,0.000000,0.000000,0.0000,0.000000,114.760000
UCity,50407.0,27.138351,22.608232,0.000000,18.888900,22.1000,27.000000,224.800000
UCityA,50407.0,1.318750,10.285338,0.000000,0.000000,0.0000,0.000000,207.262200
UHighway,50407.0,37.619422,18.891626,0.000000,28.500000,34.1000,40.579050,198.800000
UHighwayA,50407.0,1.124292,7.671446,0.000000,0.000000,0.0000,0.000000,173.143600
year,50407.0,2005.530323,13.152720,1984.000000,1993.000000,2007.0000,2017.000000,2027.000000
youSaveSpend,50407.0,-6224.497590,5764.676237,-46750.000000,-9750.000000,-5750.0000,-2500.000000,12000.000000
charge240b,50407.0,0.014552,0.311732,0.000000,0.000000,0.0000,0.000000,9.600000
phevCity,50407.0,0.374452,4.371386,0.000000,0.000000,0.0000,0.000000,111.000000
phevHwy,50407.0,0.381078,4.253044,0.000000,0.000000,0.0000,0.000000,91.000000
phevComb,50407.0,0.375365,4.285872,0.000000,0.000000,0.0000,0.000000,101.000000

In [21]:
# Estadísticas de las columnas de texto: conteo, valores únicos, moda y frecuencia
# (en pandas 3 el texto es tipo str; 'object' genera una advertencia de obsolescencia)
df_epa.describe(include="str").T

            count unique                           top   freq
drive       49221      7             Front-Wheel Drive  15913
eng_dscr    31971    628                          SIDI   9473
fuelType    50407     16                       Regular  29816
fuelType1   50405      7              Regular Gasoline  31390
make        50407    146                     Chevrolet   4600
model       50407   5688               F150 Pickup 2WD    242
mpgData     50407      2                             N  35981
trany       50396     40               Automatic 4-spd  11048
VClass      50407     34                  Compact Cars   6649
baseModel   50407   1502                        Sierra    783
guzzler      2859      3                             G   1880
trans_dscr  15044     52                         CLKUP   7809
tCharger    11787      1                             T  11787
sCharger     1167      1                             S   1167
atvType      6860     10                        Hybrid   1899
fuelType2    2013      4                           E85   1538
rangeA       2010    253                           290     78
evMotor      3636    619                    48V Li-Ion    448
mfrCode     19599     58                           GMX   2783
c240Dscr      141      5              standard charger    130
c240bDscr     135      7           80 amp dual charger     55
createdOn   50407    477  Tue Jan 01 00:00:00 EST 2013  34193
modifiedOn  50407    332  Tue Jan 01 00:00:00 EST 2013  29165
startStop   18718      2                             N   9802

In [22]:
# Conteo de columnas por tipo de dato
df_epa.dtypes.value_counts()

float64    32
int64      27
str        24
bool        1
Name: count, dtype: int64

In [23]:
# Columnas clave para la pregunta de investigación: ¿existen y cuántos nulos tienen?
cols_clave = ["co2TailpipeGpm", "displ", "cylinders", "fuelType",
              "VClass", "trany", "year", "make", "model"]
df_epa[cols_clave].isnull().sum()

co2TailpipeGpm       0
displ             1653
cylinders         1655
fuelType             0
VClass               0
trany               11
year                 0
make                 0
model                0
dtype: int64

In [24]:
# Columnas con valores nulos, ordenadas de mayor a menor
nulos = df_epa.isnull().sum()
nulos[nulos > 0].sort_values(ascending=False)

c240bDscr     50272
c240Dscr      50266
sCharger      49240
rangeA        48397
fuelType2     48394
guzzler       47548
evMotor       46771
atvType       43547
tCharger      38620
trans_dscr    35363
startStop     31689
mfrCode       30808
eng_dscr      18436
cylinders      1655
displ          1653
drive          1186
trany            11
fuelType1         2
dtype: int64

In [25]:
# ¿Qué tipo de combustible tienen los registros sin cilindrada?
df_epa[df_epa["displ"].isnull()]["fuelType"].value_counts()

fuelType
Electricity                 1607
Hydrogen                      42
Regular                        2
Electricity and Hydrogen       2
Name: count, dtype: int64

In [26]:
# Porcentaje de nulos por columna (solo las que tienen nulos)
pct_nulos = (df_epa.isnull().mean() * 100).round(2)
pct_nulos[pct_nulos > 0].sort_values(ascending=False)

c240bDscr     99.73
c240Dscr      99.72
sCharger      97.68
rangeA        96.01
fuelType2     96.01
guzzler       94.33
evMotor       92.79
atvType       86.39
tCharger      76.62
trans_dscr    70.15
startStop     62.87
mfrCode       61.12
eng_dscr      36.57
cylinders      3.28
displ          3.28
drive          2.35
trany          0.02
dtype: float64

In [27]:
# Filas duplicadas en df_epa
df_epa.duplicated().sum()

np.int64(0)

In [28]:
# Duplicados ignorando la columna 'id' (identificador único por registro)
df_epa.drop(columns="id").duplicated().sum()

np.int64(40)

**Observaciones df_epa:**
- El dataset tiene 50 407 registros y 84 columnas: 59 numéricas (32 float64, 27 int64), 24 de texto (str) y 1 booleana. Las columnas de texto aparecen como `str` porque el entorno usa pandas 3.
- 18 columnas tienen valores nulos. 13 de ellas superan el 35 % de nulos (hasta 99,7 % en `c240bDscr` y `c240Dscr`), porque describen características que solo aplican a algunos vehículos (carga eléctrica, turbo/supercargador, combustible alterno, start-stop). Son nulos estructurales y no son relevantes para la pregunta de investigación.
- Las variables clave `co2TailpipeGpm`, `fuelType`, `VClass`, `year`, `make` y `model` no tienen nulos. `cylinders` y `displ` tienen 3,28 % de nulos: se verificó que 1 651 de los 1 653 registros sin `displ` corresponden a vehículos sin motor de combustión (1 607 eléctricos, 42 de hidrógeno y 2 eléctricos/hidrógeno), por lo que son nulos estructurales. Solo 2 registros de gasolina regular son datos faltantes reales. `trany` tiene solo 11 nulos (0,02 %).
- Con 84 columnas, se requerirá seleccionar solo las variables relevantes antes del análisis.
- No hay filas duplicadas exactas, porque la columna `id` es un identificador único por registro. Sin embargo, al excluir `id` aparecen 40 registros repetidos (mismo vehículo con distinto identificador), que deberán revisarse y eliminarse en la fase de limpieza.

### 3.3 Tabla de diagnóstico estructural

| Dataset | Filas | Columnas | Tipos de datos | Valores nulos | Duplicados | Memoria |
|---|---|---|---|---|---|---|
| df_co2 | 7 385 | 12 | 7 numéricas, 5 texto | Ninguno | 1 103 | 692,5 KB |
| df_epa | 50 407 | 84 | 59 numéricas (32 float64, 27 int64), 24 texto (str), 1 bool | 18 columnas con nulos (13 con >35 %, estructurales); `displ`/`cylinders` 3,28 % (vehículos eléctricos/hidrógeno) | 0 (40 sin la columna `id`) | 32,0 MB |

## 4. Diagnóstico de problemas de calidad
Antes de construir la tabla de problemas se verifican tres posibles hallazgos adicionales: vehículos con cero emisiones, valores atípicos en las emisiones y valores de relleno en `df_epa`.

In [29]:
# Verificación 1: vehículos con 0 g/mi de CO2 por el escape, por tipo de combustible
# (los eléctricos y de hidrógeno no emiten por el escape y pueden sesgar los promedios)
df_epa[df_epa["co2TailpipeGpm"] == 0]["fuelType"].value_counts()

fuelType
Electricity                 1608
Hydrogen                      42
Electricity and Hydrogen       2
Name: count, dtype: int64

In [30]:
# Verificación 2: valores atípicos en CO2 Emissions(g/km) de df_co2 con el método IQR
# Se consideran atípicos los valores por fuera de [Q1 - 1.5*IQR, Q3 + 1.5*IQR]
q1 = df_co2["CO2 Emissions(g/km)"].quantile(0.25)
q3 = df_co2["CO2 Emissions(g/km)"].quantile(0.75)
iqr = q3 - q1
lim_inf, lim_sup = q1 - 1.5 * iqr, q3 + 1.5 * iqr
atipicos_co2 = df_co2[(df_co2["CO2 Emissions(g/km)"] < lim_inf) |
                      (df_co2["CO2 Emissions(g/km)"] > lim_sup)]
print("Límite inferior:", lim_inf, "| Límite superior:", lim_sup)
print("Registros atípicos:", len(atipicos_co2),
      f"({len(atipicos_co2) / len(df_co2) * 100:.2f} % del dataset)")

Límite inferior: 88.0 | Límite superior: 408.0
Registros atípicos: 80 (1.08 % del dataset)

In [31]:
# Verificación 3: valores de relleno (-1) en la columna 'co2' de df_epa
# Un -1 no es un nulo de Pandas, por eso info() no lo detecta ("nulo escondido")
relleno = df_epa[df_epa["co2"] == -1]
print("Registros con co2 = -1:", len(relleno),
      f"({len(relleno) / len(df_epa) * 100:.2f} % del dataset)")
if len(relleno) > 0:
    print("Años afectados:", relleno["year"].min(), "a", relleno["year"].max())

Registros con co2 = -1: 31939 (63.36 % del dataset)
Años afectados: 1984 a 2012

In [32]:
# Verificación 4: diferencia de unidades entre los dos datasets
# df_co2 mide emisiones en g/km; df_epa en g/mi (1 milla = 1.609 km)
print("df_co2 - CO2 Emissions(g/km), media:", round(df_co2["CO2 Emissions(g/km)"].mean(), 1))
print("df_epa - co2TailpipeGpm (g/mi), media:", round(df_epa["co2TailpipeGpm"].mean(), 1))
print("df_epa convertido a g/km, media:", round((df_epa["co2TailpipeGpm"] / 1.609).mean(), 1))

df_co2 - CO2 Emissions(g/km), media: 250.6
df_epa - co2TailpipeGpm (g/mi), media: 442.9
df_epa convertido a g/km, media: 275.2

### 4.1 Tabla de problemas de calidad

| # | Dataset | Problema | Evidencia | Impacto en el análisis | Acción propuesta |
|---|---|---|---|---|---|
| 1 | df_co2 | Filas duplicadas | `duplicated().sum()` = 1 103 (≈14,9 %) | Sobrerrepresenta algunos vehículos y distorsiona promedios y correlaciones | Eliminar duplicados con `drop_duplicates()` |
| 2 | df_epa | Registros repetidos ocultos por el `id` | 0 duplicados exactos, 40 al excluir `id` | Igual que el anterior, en menor escala | Eliminar duplicados ignorando la columna `id` |
| 3 | df_epa | Columnas casi vacías (nulos estructurales) | 13 columnas con más de 35 % de nulos (hasta 99,7 %) | Ruido y peso innecesario (84 columnas, 32 MB) | Seleccionar solo las variables relevantes para la pregunta |
| 4 | df_epa | Nulos en `displ` y `cylinders` | 1 653 y 1 655 nulos (3,28 %); 1 651 son eléctricos/hidrógeno y 2 son gasolina | Los nulos reales impiden analizar esos registros | Separar vehículos sin motor de combustión; eliminar los 2 nulos reales |
| 5 | df_epa | Vehículos con 0 emisiones por el escape | Verificación 1: eléctricos y de hidrógeno con `co2TailpipeGpm` = 0 | Sesgan los promedios y la relación motor–emisiones | Analizarlos aparte o excluirlos del análisis de motores de combustión |
| 6 | df_epa | Valores de relleno (-1) en `co2` | Verificación 3: registros con `co2` = -1 | `info()` los cuenta como datos válidos aunque falte el valor | Usar `co2TailpipeGpm` como variable objetivo o reemplazar -1 por `NaN` |
| 7 | df_co2 | Posibles valores atípicos en emisiones | Máximo 522 g/km frente a P75 de 288; Verificación 2 (método IQR) | Pueden influir en medias y modelos | Revisar si son vehículos reales (deportivos/alto desempeño) antes de decidir |
| 8 | Ambos | Unidades diferentes | df_co2 en g/km y L/100 km; df_epa en g/mi y mpg (Verificación 4) | No se pueden comparar ni combinar directamente | Convertir df_epa a g/km (dividir entre 1,609) |
| 9 | df_co2 | Nombres de columnas poco uniformes | Espacios, paréntesis y mayúsculas (`Engine Size(L)`, `CO2 Emissions(g/km)`) | Dificulta escribir código y unir datasets | Estandarizar nombres (minúsculas, sin espacios) |
| 10 | df_co2 | Códigos abreviados | `Fuel Type` (X, Z, D, E, N) y `Transmission` (AS6, M6…) | Sin el diccionario no se interpretan | Mapear códigos a descripciones con `Data Description.csv` |
| 11 | Ambos | Tipo de texto en pandas 3 (`str`) | `dtypes` muestra `str` en lugar de `object` | `include="object"` genera advertencias | Usar `include="str"` en el código |

## 5. Conclusiones del diagnóstico
- **df_co2** está completo (sin nulos) y sus tipos de datos son coherentes, pero tiene un problema importante de **duplicados (14,9 %)**. También tiene nombres de columnas poco uniformes y códigos que requieren el diccionario de datos.
- **df_epa** es mucho más grande y detallado (50 407 registros, 84 columnas). La mayoría de sus nulos son **estructurales**: describen características que no aplican a todos los vehículos. Sus problemas principales son el exceso de columnas, los vehículos sin motor de combustión, los valores de relleno (-1) y 40 registros repetidos.
- Las **variables clave** para la pregunta de investigación (*¿qué características del vehículo influyen en sus emisiones de CO₂ por km?*) están disponibles y casi completas en los dos datasets: emisiones, cilindrada, cilindros, tipo de combustible, transmisión y clase de vehículo.
- Los dos datasets usan **unidades distintas**, por lo que es necesario convertirlas antes de compararlos.
- **Próximos pasos (limpieza):** eliminar duplicados, seleccionar columnas relevantes de df_epa, separar los vehículos eléctricos/hidrógeno, tratar los valores -1, estandarizar nombres y unidades, y revisar los valores atípicos.